name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 8, 9, 10, 11 ]
    name: "Java ${{ matrix.java }}"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-java-${{ matrix.java }}
        restore-keys: maven-
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build
      run: mvn -B -e -Prelease -Dgpg.skip=true verify
    - name: Remove Snapshots
      run: find ~/.m2/repository -name '*-SNAPSHOT' -a -type d -print0 | xargs -0 rm -rf
